### ISSUE TITLE
H2 데이터 베이스 연동방법 정리하기

### ISSUE THREAD

**Issue by ttasjwi** [ttasjwi/tstudy#1]
# Why
- 스프링부트에서 H2 데이터 베이스를 연동하는 메뉴얼을 만들기 위함

---

# Todo

- [ ] 로컬 드라이브에서 H2 데이터베이스 설치
- [ ] SpringBoot 환경에서 H2 데이터베이스 gradle 의존관계 등록
- [ ] SpringBoot 환경에서 H2 데이터베이스 기본 설정 yml 파일
- [ ] jdbc
- [ ] jpa

---
